/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\2018_ferrari_488_gt3.glb -o src\components\Ferrari.tsx -r public -t 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2018-ferrari-488-gt3-bb14ee3833564f349a317d704a506cd3
Title: 2018 Ferrari 488 GT3
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    gt3LOD_A_BODY_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_BODY_mm_chassis_CHASSIS_0: THREE.Mesh
    gt3LOD_A_BODY_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_BODY_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BODY_mm_misc_CARBON_0: THREE.Mesh
    gt3LOD_A_BOOT_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_BOOT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BRAKES_LEFT_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_BRAKES_RIGHT_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_CHASSIS_mm_chassis_CHASSIS_0: THREE.Mesh
    gt3LOD_A_CHASSIS_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_CHASSIS_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_CHASSIS_mm_misc_CARBON_0: THREE.Mesh
    gt3LOD_A_DOOR_LEFT_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_DOOR_LEFT_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_DOOR_LEFT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_DOOR_RIGHT_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_DOOR_RIGHT_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_DOOR_RIGHT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_EXHAUST_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_chassis_CHASSIS_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_ext_CARBON_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_misc_CARBON_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_FRONTBUMPER_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_FRONT_mm_windows_BLACK_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_FRONT_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_LEFT_QUARTER_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_REAR_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_REAR_mm_windows_BLACK_GLASS_0: THREE.Mesh
    gt3LOD_A_GLASS_RIGHT_QUARTER_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_HEADLIGHT_LENS_LEFT_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_HEADLIGHT_LENS_RIGHT_mm_windows_GLASS_0: THREE.Mesh
    gt3LOD_A_HOOD_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_HOOD_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_HOOD_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_INTERIOR_mm_cab_phong8_0: THREE.Mesh
    gt3LOD_A_INTERIOR_mm_cab_phong13_0: THREE.Mesh
    gt3LOD_A_MIRROR_GLASS_LEFT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_MIRROR_GLASS_RIGHT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_MIRROR_LEFT_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_MIRROR_LEFT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_MIRROR_RIGHT_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_MIRROR_RIGHT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_REARBUMPER_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_REARBUMPER_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_REARBUMPER_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_REARBUMPER_mm_misc_CARBON_0: THREE.Mesh
    gt3LOD_A_REARBUMPER_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_TAILLIGHT_LENS_LEFT_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_TAILLIGHT_LENS_RIGHT_mm_lights_LIGHTS_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_BODY_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_BODY_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_BODY_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_HOOD_mm_badges_BADGES_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_HOOD_mm_ext_phong4_0: THREE.Mesh
    gt3LOD_A_BONNETCAM_HOOD_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BRAKE_CALIPER_FRONT_RIGHT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_BRAKE_CALIPER_REAR_RIGHT_mm_misc_MISC_0: THREE.Mesh
    gt3LOD_A_ROTOR_mm_rotor_gt3ROTOR_0: THREE.Mesh
    gt3LOD_A_TYRE_REAR_mm_tyre_gt3phong1_0: THREE.Mesh
    gt3LOD_A_TYRE_mm_tyre_gt3phong1_0: THREE.Mesh
    gt3LOD_A_WHEEL_REAR_mm_wheel_phong9_0: THREE.Mesh
    gt3LOD_A_WHEEL_mm_wheel_phong9_0: THREE.Mesh
    gt3_intLOD_A_INT_DOOR_LEFT_mm_mat00_CARBON_0: THREE.Mesh
    gt3_intLOD_A_INT_DOOR_RIGHT_mm_mat00_CARBON_0: THREE.Mesh
    gt3_intLOD_A_INT_INTERIOR_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_INTERIOR_mm_mat00_CARBON_0: THREE.Mesh
    gt3_intLOD_A_INT_INTERIOR_mm_mat01_CHROME_0: THREE.Mesh
    gt3_intLOD_A_INT_INTERIOR_mm_mat04_phong13_0: THREE.Mesh
    gt3_intLOD_A_INT_LED_EMISSIVE_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_LED_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_MIRROR_GLASS_LEFT_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_MIRROR_GLASS_RIGHT_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_MIRROR_LEFT_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_MIRROR_RIGHT_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_01_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_02_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_03_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_04_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_05_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_06_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_07_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_08_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_09_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_10_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_11_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_12_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_13_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_14_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_15_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_SHIFT_LIT_16_mm_int_INT_0: THREE.Mesh
    gt3_intLOD_A_INT_STEERING_WHEEL_mm_mat00_CARBON_0: THREE.Mesh
    gt3_intLOD_A_INT_STEERING_WHEEL_mm_sw_phong11_0: THREE.Mesh
    gt3LOD_A_WHEEL_mm_wheel1_phong9_0: THREE.Mesh
    gt3LOD_A_ROTOR_mm_rotor1_gt3ROTOR_0: THREE.Mesh
    gt3LOD_A_TYRE_mm_tyre1_gt3phong1_0: THREE.Mesh
    gt3LOD_A_ROTOR_mm_rotor2_gt3ROTOR_0: THREE.Mesh
    gt3LOD_A_ROTOR_mm_rotor3_gt3ROTOR_0: THREE.Mesh
    gt3LOD_A_WHEEL_REAR_mm_wheel1_phong9_0: THREE.Mesh
    gt3LOD_A_TYRE_REAR_mm_tyre1_______gt3phong1_0: THREE.Mesh
  }
  materials: {
    BADGES: THREE.MeshStandardMaterial
    CHASSIS: THREE.MeshStandardMaterial
    phong4: THREE.MeshStandardMaterial
    MISC: THREE.MeshStandardMaterial
    CARBON: THREE.MeshPhysicalMaterial
    LIGHTS: THREE.MeshStandardMaterial
    GLASS: THREE.MeshPhysicalMaterial
    BLACK_GLASS: THREE.MeshStandardMaterial
    phong8: THREE.MeshStandardMaterial
    phong13: THREE.MeshStandardMaterial
    gt3ROTOR: THREE.MeshStandardMaterial
    gt3phong1: THREE.MeshStandardMaterial
    phong9: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    CHROME: THREE.MeshStandardMaterial
    phong11: THREE.MeshStandardMaterial
  }
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/2018_ferrari_488_gt3.glb', true) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.gt3LOD_A_BODY_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_BODY_mm_chassis_CHASSIS_0.geometry} material={materials.CHASSIS} />
        <mesh geometry={nodes.gt3LOD_A_BODY_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_BODY_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_BODY_mm_misc_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3LOD_A_BOOT_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_BOOT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_BRAKES_LEFT_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_BRAKES_RIGHT_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_CHASSIS_mm_chassis_CHASSIS_0.geometry} material={materials.CHASSIS} />
        <mesh geometry={nodes.gt3LOD_A_CHASSIS_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_CHASSIS_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_CHASSIS_mm_misc_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_LEFT_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_LEFT_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_LEFT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_RIGHT_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_RIGHT_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_DOOR_RIGHT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_EXHAUST_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_chassis_CHASSIS_0.geometry} material={materials.CHASSIS} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_ext_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_misc_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_FRONTBUMPER_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_FRONT_mm_windows_BLACK_GLASS_0.geometry} material={materials.BLACK_GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_FRONT_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_LEFT_QUARTER_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_REAR_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_REAR_mm_windows_BLACK_GLASS_0.geometry} material={materials.BLACK_GLASS} />
        <mesh geometry={nodes.gt3LOD_A_GLASS_RIGHT_QUARTER_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_HEADLIGHT_LENS_LEFT_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_HEADLIGHT_LENS_RIGHT_mm_windows_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.gt3LOD_A_HOOD_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_HOOD_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_HOOD_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_INTERIOR_mm_cab_phong8_0.geometry} material={materials.phong8} />
        <mesh geometry={nodes.gt3LOD_A_INTERIOR_mm_cab_phong13_0.geometry} material={materials.phong13} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_GLASS_LEFT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_GLASS_RIGHT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_LEFT_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_LEFT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_RIGHT_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_MIRROR_RIGHT_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_REARBUMPER_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_REARBUMPER_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_REARBUMPER_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_REARBUMPER_mm_misc_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3LOD_A_REARBUMPER_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_TAILLIGHT_LENS_LEFT_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_TAILLIGHT_LENS_RIGHT_mm_lights_LIGHTS_0.geometry} material={materials.LIGHTS} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_BODY_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_BODY_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_BODY_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_HOOD_mm_badges_BADGES_0.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_HOOD_mm_ext_phong4_0.geometry} material={materials.phong4} />
        <mesh geometry={nodes.gt3LOD_A_BONNETCAM_HOOD_mm_misc_MISC_0.geometry} material={materials.MISC} />
        <mesh geometry={nodes.gt3LOD_A_BRAKE_CALIPER_FRONT_LEFT_mm_misc_MISC_0.geometry} material={materials.MISC} position={[1, 0.308, 1.23]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_BRAKE_CALIPER_FRONT_RIGHT_mm_misc_MISC_0.geometry} material={materials.MISC} position={[-1, 0.308, 1.23]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_BRAKE_CALIPER_REAR_LEFT_mm_misc_MISC_0.geometry} material={materials.MISC} position={[1, 0.3, -1.489]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_BRAKE_CALIPER_REAR_RIGHT_mm_misc_MISC_0.geometry} material={materials.MISC} position={[-1, 0.3, -1.489]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_ROTOR_mm_rotor_gt3ROTOR_0.geometry} material={materials.gt3ROTOR} position={[1, 0.308, 1.23]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_TYRE_REAR_mm_tyre_gt3phong1_0.geometry} material={materials.gt3phong1} position={[1, 0.3, -1.489]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_TYRE_mm_tyre_gt3phong1_0.geometry} material={materials.gt3phong1} position={[1, 0.308, 1.23]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_WHEEL_REAR_mm_wheel_phong9_0.geometry} material={materials.phong9} position={[1, 0.3, -1.489]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_WHEEL_mm_wheel_phong9_0.geometry} material={materials.phong9} position={[1, 0.308, 1.23]} scale={1.171} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_DOOR_LEFT_mm_mat00_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_DOOR_RIGHT_mm_mat00_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_INTERIOR_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_INTERIOR_mm_mat00_CARBON_0.geometry} material={materials.CARBON} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_INTERIOR_mm_mat01_CHROME_0.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_INTERIOR_mm_mat04_phong13_0.geometry} material={materials.phong13} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_LED_EMISSIVE_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_LED_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_MIRROR_GLASS_LEFT_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_MIRROR_GLASS_RIGHT_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_MIRROR_LEFT_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_MIRROR_RIGHT_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_01_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_02_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_03_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_04_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_05_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_06_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_07_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_08_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_09_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_10_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_11_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_12_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_13_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_14_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_15_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_SHIFT_LIT_16_mm_int_INT_0.geometry} material={materials.material} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_STEERING_WHEEL_mm_mat00_CARBON_0.geometry} material={materials.CARBON} position={[0.343, 0.682, 0.361]} rotation={[0.253, 0, 0]} />
        <mesh geometry={nodes.gt3_intLOD_A_INT_STEERING_WHEEL_mm_sw_phong11_0.geometry} material={materials.phong11} position={[0.343, 0.682, 0.361]} rotation={[0.253, 0, 0]} />
        <mesh geometry={nodes.gt3LOD_A_WHEEL_mm_wheel1_phong9_0.geometry} material={materials.phong9} position={[-1, 0.308, 1.23]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_ROTOR_mm_rotor1_gt3ROTOR_0.geometry} material={materials.gt3ROTOR} position={[-1, 0.308, 1.23]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_TYRE_mm_tyre1_gt3phong1_0.geometry} material={materials.gt3phong1} position={[-1, 0.308, 1.23]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.171} />
        <mesh geometry={nodes.gt3LOD_A_ROTOR_mm_rotor2_gt3ROTOR_0.geometry} material={materials.gt3ROTOR} position={[1, 0.3, -1.489]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_ROTOR_mm_rotor3_gt3ROTOR_0.geometry} material={materials.gt3ROTOR} position={[-1, 0.3, -1.489]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_WHEEL_REAR_mm_wheel1_phong9_0.geometry} material={materials.phong9} position={[-1, 0.3, -1.489]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.26} />
        <mesh geometry={nodes.gt3LOD_A_TYRE_REAR_mm_tyre1_______gt3phong1_0.geometry} material={materials.gt3phong1} position={[-1, 0.3, -1.489]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.26} />
      </group>
    </group>
  )
}

useGLTF.preload('/2018_ferrari_488_gt3.glb', true)
